ALTER TABLE "User" ALTER COLUMN "primaryCurrency" SET DEFAULT 'CRC';
ALTER TABLE "Workspace" ADD COLUMN "primaryCurrency" CHAR(3) NOT NULL DEFAULT 'CRC';
CREATE TYPE "PaymentMethodType" AS ENUM ('DEBIT','CASH','CREDIT_CARD');
CREATE TYPE "RecurringKind" AS ENUM ('MEMBERSHIP','SERVICE');
CREATE TABLE "SavingsGoal" ("id" TEXT NOT NULL, "userId" TEXT NOT NULL, "workspaceId" TEXT, "name" TEXT NOT NULL, "target" DECIMAL(12,2) NOT NULL, "balance" DECIMAL(12,2) NOT NULL DEFAULT 0, "currency" CHAR(3) NOT NULL DEFAULT 'CRC', "targetDate" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "SavingsGoal_pkey" PRIMARY KEY ("id"));
CREATE TABLE "SavingsContribution" ("id" TEXT NOT NULL, "goalId" TEXT NOT NULL, "amount" DECIMAL(12,2) NOT NULL, "date" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "note" TEXT, CONSTRAINT "SavingsContribution_pkey" PRIMARY KEY ("id"));
CREATE TABLE "PaymentMethod" ("id" TEXT NOT NULL, "userId" TEXT NOT NULL, "workspaceId" TEXT, "name" TEXT NOT NULL, "type" "PaymentMethodType" NOT NULL, "creditLimit" DECIMAL(12,2), "closingDay" INTEGER, "paymentDay" INTEGER, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "PaymentMethod_pkey" PRIMARY KEY ("id"));
ALTER TABLE "Transaction" ADD COLUMN "paymentMethodId" TEXT;
ALTER TABLE "RecurringRule" ADD COLUMN "kind" "RecurringKind" NOT NULL DEFAULT 'SERVICE';
ALTER TABLE "RecurringRule" ADD COLUMN "provider" TEXT;
ALTER TABLE "RecurringRule" ADD COLUMN "chargeDay" INTEGER;
ALTER TABLE "RecurringRule" ADD COLUMN "paymentMethodId" TEXT;
CREATE INDEX "SavingsGoal_userId_workspaceId_idx" ON "SavingsGoal"("userId","workspaceId");
CREATE INDEX "SavingsContribution_goalId_date_idx" ON "SavingsContribution"("goalId","date");
CREATE INDEX "PaymentMethod_userId_workspaceId_idx" ON "PaymentMethod"("userId","workspaceId");
CREATE INDEX "Transaction_paymentMethodId_idx" ON "Transaction"("paymentMethodId");
ALTER TABLE "SavingsGoal" ADD CONSTRAINT "SavingsGoal_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE, ADD CONSTRAINT "SavingsGoal_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "Workspace"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "SavingsContribution" ADD CONSTRAINT "SavingsContribution_goalId_fkey" FOREIGN KEY ("goalId") REFERENCES "SavingsGoal"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "PaymentMethod" ADD CONSTRAINT "PaymentMethod_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE, ADD CONSTRAINT "PaymentMethod_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "Workspace"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Transaction" ADD CONSTRAINT "Transaction_paymentMethodId_fkey" FOREIGN KEY ("paymentMethodId") REFERENCES "PaymentMethod"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "RecurringRule" ADD CONSTRAINT "RecurringRule_paymentMethodId_fkey" FOREIGN KEY ("paymentMethodId") REFERENCES "PaymentMethod"("id") ON DELETE SET NULL ON UPDATE CASCADE;
